require("src.scene")
require("src.conversion")
require("src.itemTypes")
require("src.items")

require("src.Scenes.scenes")
require("src.Scenes.pitFallScenes")
require("src.Scenes.banditAttackScenes")
require("src.Scenes.beginningScenes")
require("src.Scenes.castleScenes")
require("src.Scenes.fairyScenes")
require("src.Scenes.hunterHutScenes")